services:
  faq-api:
    build: .
    ports:
      - "8000:8000"  # твой FastAPI API на этом порту
    volumes:
      - chroma_data:/data/chroma
    environment:
      - USE_OPENAI=false
    depends_on:
      - chromadb
    command: >
      bash -c "uvicorn src.api:app --host 0.0.0.0 --port 8000"

  chromadb:
    image: chromadb/chroma
    container_name: chromadb-server
    ports:
      - "8001:8000"  # Внешний порт 8001 → внутренний 8000
    volumes:
      - chroma_data:/chroma/.chroma
    environment:
      - IS_PERSISTENT=TRUE

volumes:
  chroma_data:

