services:
  faq-api:
    build: .
    container_name: faq-api
    ports:
      - "8000:8000"  # FastAPI наружу
    volumes:
      - .:/app
    command: >
      uvicorn src.api:app --host 0.0.0.0 --port 8000



