name: QA tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start ChromaDB server
        run: docker run -d -p 8000:8000 -v ${{ github.workspace }}/data/chroma:/chroma-data chromadb/chroma run --path /chroma-data
      - name: Run ingestion (build vector store)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          USE_OPENAI: 'false'
        run: PYTHONPATH=./src python -m src.ingest
      - name: Run QA tests
        run: PYTHONPATH=./src python -m tests.qa_check
