name: QA tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Wait for ChromaDB server
        run: |
          echo "Waiting for ChromaDB /api/v2/heartbeat..."
          for i in {1..20}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" https://chroma-server-cydq.onrender.com/api/v2/heartbeat)
            echo "Try $i: HTTP $code"
            if [ "$code" = "200" ]; then
              echo "ChromaDB is ready."
              break
            fi
            sleep 5
          done     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ingestion (build vector store)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          USE_OPENAI: 'false'
        run: PYTHONPATH=./src python -m src.ingest
      - name: Run QA tests
        run: PYTHONPATH=./src python -m tests.qa_check
