name: QA tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COLLECTION_NAME: banking-faq
    steps:
      - uses: actions/checkout@v3       
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docker.txt
      - name: Run QA tests
        run: PYTHONPATH=./src python -m tests.qa_check
